export const teams = [
  {
    name: 'Oleksii',
    surName: 'Tsarenko',
    position: 'Team-lead',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/olexii_tsarenko-min-removebg-preview.jpg'),
  },
  {
    name: 'Iryna',
    surName: 'Trynkal',
    position: 'Scrum-master',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/iryna_trynkal-removebg-preview.jpg'),
  },
  {
    name: 'Oleksandr',
    surName: 'Domin',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/oleksandr_domin-removebg-preview.jpg'),
  },
  {
    name: 'Andrii',
    surName: 'Tsokur',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/andrii_tsokur-removebg-preview.jpg'),
  },
  {
    name: 'Andrii',
    surName: 'Svyntsov',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/andrii_svintsov-removebg-preview.jpg'),
  },
  {
    name: 'Serhii',
    surName: 'Rozhok',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/serhii_rozhok-removebg-preview.jpg'),
  },
  {
    name: 'Maksym',
    surName: 'Kartawcew',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/MaksK-min-removebg-preview.png'),
  },
  {
    name: 'Nataliia',
    surName: 'Olishkevych',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/natali-min-removebg-preview.jpg'),
  },

  {
    name: 'Andrii',
    surName: 'Kruk',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/90782810_105360824447942_776154535176437760_n-removebg-preview.jpg'),
  },

  {
    name: 'Vitalii',
    surName: 'Tarasenko',
    position: 'Developer',
    git: 'https://github.com/zhdima',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/vitalii_tarasenko-removebg-preview.jpg'),
  },
  {
    name: 'Stanislav',
    surName: 'Izotov',
    position: 'Developer',
    git: 'https://github.com/Stanislav-i',
    linkedin: 'https://www.linkedin.com/in/stanislav-izotov-dev',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/Stanislav_Izotov-removebg-preview.png'),
  },
  {
    name: 'Vladyslav',
    surName: 'Slobodeniuk',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/vladyslav_slobodeniuk-removebg-preview.jpg'),
  },
  {
    name: 'Andrii',
    surName: 'Ishchenko',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
    description: ['Organization'],
    avatar: require('../../Pictures/team-developer/andrii-min-removebg-preview.jpg'),
  },
];
