export const teams = [
  {
    name: 'Oleksii',
    surName: 'Tsarenko',
    position: 'Team-lead',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Iryna',
    surName: 'Trynkal',
    position: 'Scrum-master',
    git: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Andrii',
    surName: 'Tsokur',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Andrii',
    surName: 'Svyntsov',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Serhii',
    surName: 'Rozhok',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Maksym',
    surName: 'Kartawcew',
    position: 'Developer',
    git: 'https://github.com/Erlara',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Nataliia',
    surName: 'Olishkevych',
    position: 'Developer',
    git: 'https://github.com/Anton-Logvinenko',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Oleksandr',
    surName: 'Domin',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Andrii',
    surName: 'Ishchenko',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Andrii',
    surName: 'Kruk',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Vladyslav',
    surName: 'Slobodeniuk',
    position: 'Developer',
    git: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Vitalii',
    surName: 'Tarasenko',
    position: 'Developer',
    git: 'https://github.com/zhdima',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'Stanislav',
    surName: 'Izotov',
    position: 'Developer',
    git: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/in/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
];
