export const teams = [
  {
    name: 'name',
    surName: 'name',
    position: 'Team-lead',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Scrum-master',
    git: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com/Erlara',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com/Anton-Logvinenko',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com/zhdima',
    linkedin: 'https://www.linkedin.com/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
  {
    name: 'name',
    surName: 'name',
    position: 'Developer',
    git: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/in/',
    description: ['Organization'],
    avatar: require('../../Pictures/avatar.jpg'),
  },
];
